### ISSUE TITLE
wrong?

### ISSUE THREAD

**Issue by lunarjoll** [mmarkdown/mmark#46]
# To help us debug your issue please add these details.
I use go get to install 
## What went wrong?
-html
## What version of mmark are you using?
master
## What command line did you use?
bash
## What platform (Linux/Apple/Windows)?
linux
- [ ] Linux
- [ ] Apple
- [ ] Windows

## What is the *most* minimal markdown snippets that shows the problem?
mmark -html ~/go/src/github.com/mmarkdown/mmark/rfc/3514.md > x.html

result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x53d7b3]

goroutine 1 [running]:
github.com/mmarkdown/mmark/render/mhtml.bibliographyItem(0x5cfde0, 0xc000114930, 0xc000114690, 0xc000114901)
	/home/king/go/src/github.com/mmarkdown/mmark/render/mhtml/hook.go:102 +0x183
github.com/mmarkdown/mmark/render/mhtml.RenderHook(0x5cfde0, 0xc000114930, 0x5d1d00, 0xc000114690, 0x1, 0x5cfde0, 0xc0000d3718)
	/home/king/go/src/github.com/mmarkdown/mmark/render/mhtml/hook.go:37 +0x38c
github.com/gomarkdown/markdown/html.(*Renderer).RenderNode(0xc0000e8b40, 0x5cfde0, 0xc000114930, 0x5d1d00, 0xc000114690, 0x1, 0x0)
	/home/king/go/src/github.com/gomarkdown/markdown/html/renderer.go:914 +0x16ce
github.com/gomarkdown/markdown.Render.func1(0x5d1d00, 0xc000114690, 0x4ff401, 0xc0000e8b40)
	/home/king/go/src/github.com/gomarkdown/markdown/markdown.go:63 +0x61
github.com/gomarkdown/markdown/ast.NodeVisitorFunc.Visit(0xc00000bd20, 0x5d1d00, 0xc000114690, 0x1, 0xc0000d38e8)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:547 +0x43
github.com/gomarkdown/markdown/ast.Walk(0x5d1d00, 0xc000114690, 0x5d0060, 0xc00000bd20, 0x0)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:519 +0x70
github.com/gomarkdown/markdown/ast.Walk(0x5d1ca0, 0xc0001148c0, 0x5d0060, 0xc00000bd20, 0x0)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:530 +0x1ba
github.com/gomarkdown/markdown/ast.Walk(0x5d1280, 0xc000114000, 0x5d0060, 0xc00000bd20, 0x0)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:530 +0x1ba
github.com/gomarkdown/markdown/ast.Walk(0x5d1220, 0xc000064480, 0x5d0060, 0xc00000bd20, 0xc00000bd20)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:530 +0x1ba
github.com/gomarkdown/markdown/ast.WalkFunc(0x5d1220, 0xc000064480, 0xc00000bd20)
	/home/king/go/src/github.com/gomarkdown/markdown/ast/node.go:553 +0x4b
github.com/gomarkdown/markdown.Render(0x5d1220, 0xc000064480, 0x5d0580, 0xc0000e8b40, 0x5a9adc, 0x13, 0x5a861f)
	/home/king/go/src/github.com/gomarkdown/markdown/markdown.go:62 +0xd8
main.main()
	/home/king/go/src/github.com/mmarkdown/mmark/mmark.go:171 +0x67

**Comment by miekg** [comment]
#46 out with a fix and some reanabled tests that would have caught this.

**Comment by lunarjoll** [comment]
？？？
V2.0.30 success and v2.0.33 I run failed

**Comment by miekg** [comment]
In master

On 2 Jan 2019 18:59, "lunarjoll" <notifications@github.com> wrote:

？？？
V2.0.30 success and v2.0.33 I run failed

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mmarkdown/mmark/issues/46#issuecomment-450935358>, or mute
the thread

**Comment by miekg** [comment]
released https://github.com/mmarkdown/mmark/releases/tag/v2.0.35
